### ISSUE TITLE
Ubuntu/Debian clickhouse pkg: 404  Not Found

### ISSUE THREAD

**Issue by Denkaspb** [ernestas-poskus/chef-clickhouse#15]
Hello.

In  libraries: clickhouse_base.rb uses repo which not found for installing clickhouse package on ubuntu/debian:

`      def install_clickhouse_repository
        case node['platform']
        when 'rhel', 'centos'
          execute 'curl -s https://packagecloud.io/install/repositories/Altinity/clickhouse/script.rpm.sh | sudo bash' do
            creates '/etc/yum.repos.d/Altinity_clickhouse.repo'
          end
        when 'ubuntu', 'debian'
          execute 'apt_update_for_chef_clickhouse' do
            command %(apt-get update)
            action :nothing
          end

          execute 'curl -s https://packagecloud.io/install/repositories/Altinity/clickhouse/script.deb.sh | sudo bash' do
            creates '/etc/apt/sources.list.d/Altinity_clickhouse.list'
            notifies :run, 'execute[apt_update_for_chef_clickhouse]', :immediate
          end
        end
`

Now new apt repository which consist clickhouse package its:
 http://repo.yandex.ru/clickhouse/deb/stable/ main/

**Comment by DeathBorn** [comment]
we deprecated ubuntu/debian support and updated cookbook for new versions
